"""Add plan table

Revision ID: 0f2f5729e6d4
Revises: 1696bbacab70
Create Date: 2023-12-09 18:53:39.062090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision: str = '0f2f5729e6d4'
down_revision: Union[str, None] = '1696bbacab70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_methods')
    op.add_column('users', sa.Column('stripe_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'stripe_id')
    op.create_table('payment_methods',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='payment_methods_pkey')
    )
    # ### end Alembic commands ###
