"""add table prompt for tone and many model

Revision ID: 116464f3a0f7
Revises: 339cfed14410
Create Date: 2023-12-20 23:45:00.138917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision: str = '116464f3a0f7'
down_revision: Union[str, None] = '339cfed14410'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('input_prompts', sa.Column('feature_id', sa.Integer(), nullable=True))
    op.create_unique_constraint('unique input prompts', 'input_prompts', ['feature_id', 'model_id'])
    op.drop_constraint('input_prompts_tone_id_fkey', 'input_prompts', type_='foreignkey')
    op.create_foreign_key(None, 'input_prompts', 'features', ['feature_id'], ['id'])
    op.drop_column('input_prompts', 'tone_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('input_prompts', sa.Column('tone_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'input_prompts', type_='foreignkey')
    op.create_foreign_key('input_prompts_tone_id_fkey', 'input_prompts', 'tones', ['tone_id'], ['id'])
    op.drop_constraint('unique input prompts', 'input_prompts', type_='unique')
    op.drop_column('input_prompts', 'feature_id')
    # ### end Alembic commands ###
