"""init

Revision ID: 1ca44a84be7d
Revises: 
Create Date: 2023-12-07 19:36:43.605317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # added
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1ca44a84be7d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('coin')
    op.drop_table('coins')
    op.alter_column('features', 'name',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=False)
    op.alter_column('features', 'date_of_create',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.Date(),
               nullable=False)
    op.alter_column('features', 'url',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=False)
    op.add_column('users', sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('access_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('users', 'firebase_id',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('users', 'name',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('users', 'profilepic',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.drop_index('idx_user_firebase_id', table_name='users')
    op.drop_index('idx_user_stripe_id', table_name='users')
    op.drop_constraint('idx_users_stripe_id', 'users', type_='unique')
    op.drop_column('users', 'stripe_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('stripe_id', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_unique_constraint('idx_users_stripe_id', 'users', ['stripe_id'])
    op.create_index('idx_user_stripe_id', 'users', ['stripe_id'], unique=False)
    op.create_index('idx_user_firebase_id', 'users', ['firebase_id'], unique=False)
    op.alter_column('users', 'profilepic',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'firebase_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('users', 'access_token')
    op.drop_column('users', 'platform')
    op.alter_column('features', 'url',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('features', 'date_of_create',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('features', 'name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               nullable=True)
    op.create_table('coins',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_users_coin'),
    sa.PrimaryKeyConstraint('id', name='coins_pkey')
    )
    op.create_table('coin',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='coin_pkey')
    )
    op.create_table('payments',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('coin', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('transaction_stripe_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('datetime', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('payment_method_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('feature_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], name='fk_features_payment'),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_methods.id'], name='fk_payment_methods_payments'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_users_payment'),
    sa.PrimaryKeyConstraint('id', name='payments_pkey')
    )
    # ### end Alembic commands ###
