"""add table prompt for tone and many model

Revision ID: 1ec6e9c40892
Revises: 8a78623205f8
Create Date: 2023-12-20 22:18:50.766154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision: str = '1ec6e9c40892'
down_revision: Union[str, None] = '8a78623205f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tones', 'prompt')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tones', sa.Column('prompt', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
