"""add column language to input prompt

Revision ID: 24c695366aae
Revises: 116464f3a0f7
Create Date: 2023-12-21 00:49:35.578525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision: str = '24c695366aae'
down_revision: Union[str, None] = '116464f3a0f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('input_prompts', sa.Column('language_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'input_prompts', 'languages', ['language_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'input_prompts', type_='foreignkey')
    op.drop_column('input_prompts', 'language_id')
    # ### end Alembic commands ###
