"""add table prompt for tone and many model

Revision ID: 339cfed14410
Revises: ce62acc99f54
Create Date: 2023-12-20 22:25:06.955834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision: str = '339cfed14410'
down_revision: Union[str, None] = 'ce62acc99f54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('input_prompts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt_input', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tone_id', sa.Integer(), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.ForeignKeyConstraint(['tone_id'], ['tones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('inputprompts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inputprompts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('prompt_input', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tone_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('model_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], name='inputprompts_model_id_fkey'),
    sa.ForeignKeyConstraint(['tone_id'], ['tones.id'], name='inputprompts_tone_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='inputprompts_pkey')
    )
    op.drop_table('input_prompts')
    # ### end Alembic commands ###
