"""add column language to input prompt

Revision ID: beea56e1feb1
Revises: 24c695366aae
Create Date: 2023-12-21 00:50:49.161178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision: str = 'beea56e1feb1'
down_revision: Union[str, None] = '24c695366aae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique input prompts', 'input_prompts', type_='unique')
    op.create_unique_constraint('unique input prompts', 'input_prompts', ['feature_id', 'model_id', 'language_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique input prompts', 'input_prompts', type_='unique')
    op.create_unique_constraint('unique input prompts', 'input_prompts', ['feature_id', 'model_id'])
    # ### end Alembic commands ###
