"""add table prompt for tone and many model

Revision ID: ce62acc99f54
Revises: 1ec6e9c40892
Create Date: 2023-12-20 22:20:43.798156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision: str = 'ce62acc99f54'
down_revision: Union[str, None] = '1ec6e9c40892'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inputprompts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt_input', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tone_id', sa.Integer(), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.ForeignKeyConstraint(['tone_id'], ['tones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inputprompts')
    # ### end Alembic commands ###
