name: Release a prod to stating
on:
  release:
    types: [published]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: Configure Docker
      run: |
        gcloud auth configure-docker
        gcloud auth configure-docker asia-southeast1-docker.pkg.dev --quiet
    
    - name: create-cred-firebase-json
      id: create-cred-firebase-json
      uses: jsdaniell/create-json@v1.2.2
      with:
        name: "firebase-credential.json"
        json: ${{secrets.FIREBASE_KEY}}
    
    - name: create-cred-vertex-json
      id: create-cred-vertex-json
      uses: jsdaniell/create-json@v1.2.2
      with:
        name: "gcp_sa_key.json"
        json: ${{secrets.GCP_VERTEX_KEY}}

    - name: Build and push Docker image
      run: |
        docker build -t asia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/main/prompt-lab-be:${{ github.sha }} .
        docker push asia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/main/prompt-lab-be:${{ github.sha }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy prompt-lab-be \
        --image asia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/main/prompt-lab-be:${{ github.sha }} \
        --region asia-southeast1 \
        --platform managed \
        --allow-unauthenticated \
        --set-env-vars OPENAI_KEY=${{ secrets.OPENAI_KEY }},DB_USER=${{ secrets.DB_USER_DEV }},DB_PASSWORD=${{ secrets.DB_PASSWORD_DEV }},DB_HOST=${{ secrets.DB_HOST }},DB_PORT=${{ secrets.DB_PORT_DEV }},DB_NAME=${{ secrets.DB_NAME}},FIREBASE_API_KEY=${{secrets.FIREBASE_API_KEY}},ENV=PROD,GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }},STRIPE_KEY=${{ secrets.STRIPE_KEY }},GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }} \
        --max-instances=10 \
        --memory 2Gi \
        --concurrency=80 \
        --tag=prod \
        --timeout=300s
    - name: update tags stating
      run: |
        gcloud run services update-traffic prompt-lab-be \
        --to-tags=prod=100 \
        --region=asia-southeast1
