name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - backend/dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.3.0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Configure Docker
      run: |
        gcloud auth configure-docker

    - name: create-cred-json
      id: create-cred-json
      uses: jsdaniell/create-json@v1.2.2
      with:
        name: "firebase-credential.json"
        json: ${{secrets.FIREBASE_KEY}}

    - name: Build and push Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/prompt-lab-be-dev:${{ github.sha }} .
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/prompt-lab-be-dev:${{ github.sha }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy prompt-lab-be-dev \
        --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/prompt-lab-be-dev:${{ github.sha }} \
        --region asia-southeast1 \
        --platform managed \
        --allow-unauthenticated \
        --set-env-vars OPANAI_KEY=${{ secrets.OPENAI_KEY }},DB_USER=${{ secrets.DB_USER_DEV }},DB_PASSWORD=${{ secrets.DB_PASSWORD_DEV }},DB_HOST=${{ secrets.DB_HOST }},DB_PORT=${{ secrets.DB_PORT_DEV }},DB_NAME=${{ secrets.DB_NAME_DEV}} \
        --max-instances=10
